import { jsPDF } from "jspdf";

// Text-based PDF generation (reliable; avoids html2canvas + Tailwind oklch issues).

const MARGIN = 14;
const LINE = 6;

const addWrapped = (doc, text, x, y, maxWidth) => {
  const lines = doc.splitTextToSize(text || "", maxWidth);
  doc.text(lines, x, y);
  return y + lines.length * LINE;
};

const ensureSpace = (doc, y, needed = LINE) => {
  const pageHeight = doc.internal.pageSize.getHeight();
  if (y + needed > pageHeight - MARGIN) {
    doc.addPage();
    return MARGIN;
  }
  return y;
};

/** Export a single medical report (summary + lab values) as a PDF. */
export const exportReportPdf = (report) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const contentW = pageWidth - MARGIN * 2;
  let y = MARGIN;

  doc.setFontSize(16);
  doc.text("AuraHealth — Lab Report", MARGIN, y);
  y += LINE * 1.6;

  doc.setFontSize(10);
  doc.setTextColor(90);
  y = addWrapped(doc, `File: ${report.filename || "report"}`, MARGIN, y, contentW);
  if (report.created_at) {
    y = addWrapped(doc, `Date: ${new Date(report.created_at).toLocaleString()}`, MARGIN, y, contentW);
  }
  doc.setTextColor(0);
  y += LINE * 0.5;

  if (report.summary) {
    y = ensureSpace(doc, y);
    doc.setFontSize(12);
    doc.text("AI Summary", MARGIN, y);
    y += LINE;
    doc.setFontSize(10);
    y = addWrapped(doc, report.summary, MARGIN, y, contentW);
    y += LINE * 0.5;
  }

  const labs = report.lab_values || [];
  if (labs.length) {
    y = ensureSpace(doc, y);
    doc.setFontSize(12);
    doc.text("Lab Values", MARGIN, y);
    y += LINE;

    doc.setFontSize(9);
    doc.setTextColor(120);
    doc.text("Test", MARGIN, y);
    doc.text("Value", MARGIN + 80, y);
    doc.text("Status", MARGIN + 120, y);
    doc.text("Reference", MARGIN + 150, y);
    doc.setTextColor(0);
    y += LINE * 0.6;
    doc.setDrawColor(210);
    doc.line(MARGIN, y, pageWidth - MARGIN, y);
    y += LINE * 0.7;

    doc.setFontSize(9);
    labs.forEach((l) => {
      y = ensureSpace(doc, y);
      doc.text(String(l.test_name || "").slice(0, 40), MARGIN, y);
      doc.text(`${l.value ?? ""} ${l.unit || ""}`.trim(), MARGIN + 80, y);
      doc.text(String(l.status || ""), MARGIN + 120, y);
      doc.text(String(l.reference_range || "—"), MARGIN + 150, y);
      y += LINE;
    });
  }

  y = ensureSpace(doc, y, LINE * 2);
  y += LINE;
  doc.setFontSize(8);
  doc.setTextColor(140);
  addWrapped(
    doc,
    "Generated by AuraHealth. This is an automated overview, not medical advice. Consult a physician.",
    MARGIN,
    y,
    contentW
  );

  const safeName = (report.filename || "report").replace(/\.[^.]+$/, "");
  doc.save(`AuraHealth_Report_${safeName}.pdf`);
};

/** Export the dashboard's latest biomarkers + alerts as a PDF. */
export const exportDashboardPdf = ({ biomarkers = [], alerts = [], userName = "" }) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const contentW = pageWidth - MARGIN * 2;
  let y = MARGIN;

  doc.setFontSize(16);
  doc.text("AuraHealth — Health Snapshot", MARGIN, y);
  y += LINE * 1.6;
  doc.setFontSize(10);
  doc.setTextColor(90);
  if (userName) y = addWrapped(doc, `Name: ${userName}`, MARGIN, y, contentW);
  y = addWrapped(doc, `Generated: ${new Date().toLocaleString()}`, MARGIN, y, contentW);
  doc.setTextColor(0);
  y += LINE * 0.5;

  doc.setFontSize(12);
  doc.text("Latest Biomarkers", MARGIN, y);
  y += LINE;
  doc.setFontSize(10);
  if (biomarkers.length === 0) {
    y = addWrapped(doc, "No biomarker data available.", MARGIN, y, contentW);
  } else {
    biomarkers.forEach((b) => {
      y = ensureSpace(doc, y);
      y = addWrapped(
        doc,
        `${b.label}: ${b.value ?? "—"} ${b.unit || ""} (${b.status || "—"})`,
        MARGIN,
        y,
        contentW
      );
    });
  }
  y += LINE * 0.5;

  if (alerts.length) {
    y = ensureSpace(doc, y);
    doc.setFontSize(12);
    doc.text("Alerts", MARGIN, y);
    y += LINE;
    doc.setFontSize(10);
    alerts.forEach((a) => {
      y = ensureSpace(doc, y);
      y = addWrapped(doc, `• ${a}`, MARGIN, y, contentW);
    });
  }

  doc.save("AuraHealth_Health_Snapshot.pdf");
};
